# Generated by Django 5.1.7 on 2025-03-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('owner', 'Owner'), ('staff', 'Staff'), ('delivery', 'Delivery')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('locations', models.JSONField(default=list)),
            ],
        ),
    ]
