# Generated by Django 5.1.7 on 2025-03-13 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_slug_product_slug_subcategory_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='slug',
        ),
    ]
